baseURL = 'https://myblog-8fq.pages.dev/'
locale = 'zh-cn'
title = '学海云舟'
theme = 'PaperMod'

[pagination]
paperSize = 5

[params]
ShowReadingTime = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
